"""Base strategy class that all strategies must inherit from."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

import pandas as pd


class Signal(Enum):
    LONG = "long"
    SHORT = "short"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    HOLD = "hold"


@dataclass
class TradeSignal:
    """Trading signal generated by a strategy."""

    signal: Signal
    symbol: str
    price: float
    timestamp: pd.Timestamp
    confidence: float = 0.0  # 0-1
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    metadata: dict = field(default_factory=dict)
    reason: str = ""  # Human-readable rationale for this signal


class BaseStrategy(ABC):
    """Abstract base class for all trading strategies."""

    name: str = "base"

    @abstractmethod
    def generate_signal(self, df: pd.DataFrame) -> TradeSignal:
        """Generate a trading signal from OHLCV data.

        Args:
            df: OHLCV DataFrame with indicators.

        Returns:
            TradeSignal with entry/exit decision.
        """
        ...

    @abstractmethod
    def get_required_indicators(self) -> list[str]:
        """Return list of indicator column names this strategy needs."""
        ...
